### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/AEIOU#17]
There is a need to release a new version of the activity on ASLO.

**Comment by quozl** [comment]
Sorry, but ASLO is for Python 2 activities.  We can split into branches if necessary.

**Comment by quozl** [comment]
http://activities.sugarlabs.org/en-US/sugar/addon/4626
https://github.com/sugarlabs/AEIOU/tree/python2
https://github.com/sugarlabs/AEIOU/releases/tag/v7
